credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$1B1vsBaeaAulcQcQriwON.B2Ye7HkgmJHmK7mYIgB6lDmEHTqlWLS
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: 2b$12$N2ppdP0ugChuJz7PiQtcV.nj.UrSAD5C40TsMJawgxGlajjWFjwTK
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
